services:
  kafka:
    environment:
      KAFKA_EXTERNAL_HOST: "${KAFKA_NODE_HOST:?Set KAFKA_NODE_HOST}"
      KAFKA_EXTERNAL_PORT: 9094

  kafka-2:
    environment:
      KAFKA_EXTERNAL_HOST: "${KAFKA_NODE_HOST:?Set KAFKA_NODE_HOST}"
      KAFKA_EXTERNAL_PORT: 9095

  kafka-3:
    environment:
      KAFKA_EXTERNAL_HOST: "${KAFKA_NODE_HOST:?Set KAFKA_NODE_HOST}"
      KAFKA_EXTERNAL_PORT: 9096
