services:
  kafka:
    environment:
      KAFKA_LISTENERS: "CONTROLLER://:9093,PLAINTEXT://:9092,NODE://:9094"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,NODE://${KAFKA_NODE_HOST:?Set KAFKA_NODE_HOST}:9094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,NODE:PLAINTEXT"
